services:
  # Victor API Service
  victor-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5433
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=dcs_user
      - POSTGRES_PASSWORD=secure_password
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - LITELLM_BASE_URL=http://host.docker.internal:4000
    volumes:
      - ../:/app/src
    restart: unless-stopped
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # n8n for workflow automation
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=host.docker.internal
      - DB_POSTGRESDB_PORT=5433
      - DB_POSTGRESDB_DATABASE=vectordb
      - DB_POSTGRESDB_USER=dcs_user
      - DB_POSTGRESDB_PASSWORD=secure_password
      - N8N_HOST=${N8N_HOST:-ai.victorromeosierra.com}
      - N8N_PORT=5678
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL:-https://ai.victorromeosierra.com/n8n/}
      - EXECUTIONS_PROCESS=main
      - VICTOR_API_URL=http://host.docker.internal:8000
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    volumes:
      - n8n_storage:/home/node/.n8n
      - ../automation/workflows:/home/node/.n8n/workflows
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_storage: