services:
  # Victor API Service
  victor-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - POSTGRES_PORT=${POSTGRES_PORT:-5433}
      - POSTGRES_DB=${POSTGRES_DB:-vectordb}
      - POSTGRES_USER=${POSTGRES_USER:-victor_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - LITELLM_BASE_URL=${LITELLM_BASE_URL:-http://host.docker.internal:4000}
    volumes:
      - ../:/app/src
    restart: unless-stopped
    network_mode: bridge

  # n8n for workflow automation
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST:-localhost}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT:-5433}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-vectordb}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-victor_user}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - EXECUTIONS_PROCESS=main
      - VICTOR_API_URL=http://victor-api:8000
    volumes:
      - n8n_storage:/home/node/.n8n
      - ../automation/workflows:/home/node/.n8n/workflows
    network_mode: bridge

volumes:
  n8n_storage: