services:
  # Victor API Service
  victor-api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - INSTALL_ML_PACKAGES=${INSTALL_ML_PACKAGES:-false}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://dcs_user:secure_password@host.docker.internal:5433/vectordb
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5433
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=dcs_user
      - POSTGRES_PASSWORD=secure_password
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER:-ollama}
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBED_MODEL:-nomic-embed-text}
      - SEARCH_LIMIT=${SEARCH_LIMIT:-10}
    volumes:
      - ../:/app/src
    restart: unless-stopped
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # n8n for workflow automation
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=host.docker.internal
      - DB_POSTGRESDB_PORT=5433
      - DB_POSTGRESDB_DATABASE=vectordb
      - DB_POSTGRESDB_USER=dcs_user
      - DB_POSTGRESDB_PASSWORD=secure_password
      - N8N_HOST=${N8N_HOST:-n8n.victorromeosierra.com}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL:-https://n8n.victorromeosierra.com/}
      - N8N_EDITOR_BASE_URL=https://n8n.victorromeosierra.com/
      - EXECUTIONS_PROCESS=main
      - VICTOR_API_URL=http://host.docker.internal:8000
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    volumes:
      - n8n_storage:/home/node/.n8n
      - ../automation/workflows:/home/node/.n8n/workflows
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_storage: