# LiteLLM Configuration for Victor with RAG Integration

model_list:
  # Local Ollama models with DCS RAG enhancement
  - model_name: dcs-codellama
    litellm_params:
      model: ollama/codellama
      api_base: http://localhost:11434
      stream: true
    model_info:
      mode: chat
      supports_function_calling: false
      description: "CodeLlama optimized for DCS Lua development with RAG context"
      
  - model_name: dcs-llama3
    litellm_params:
      model: ollama/llama3
      api_base: http://localhost:11434
      stream: true
    model_info:
      mode: chat
      supports_function_calling: false
      description: "Llama3 with DCS RAG context for general assistance"

  # Fallback models without RAG (for non-DCS queries)
  - model_name: codellama
    litellm_params:
      model: ollama/codellama
      api_base: http://localhost:11434
      stream: true
    model_info:
      mode: chat
      description: "Standard CodeLlama without RAG enhancement"
      
  - model_name: llama3
    litellm_params:
      model: ollama/llama3
      api_base: http://localhost:11434
      stream: true
    model_info:
      mode: chat
      description: "Standard Llama3 without RAG enhancement"

# Environment variables for Victor integration
environment_variables:
  VICTOR_API_URL: http://localhost:8000
  VICTOR_TIMEOUT: "10.0"
  VICTOR_RAG_ENABLED: "true"
  OLLAMA_BASE_URL: http://localhost:11434

# General settings
general_settings:
  # Master key for admin access (set via env var)
  master_key: null
  
  # Database for usage tracking (optional)
  database_url: null
  
  # Enable UI for model management
  ui: true
  
  # Custom callbacks and hooks
  callbacks: []
  
  # Request settings
  max_budget: null
  budget_duration: null
  
  # Timeout settings
  request_timeout: 300
  
  # Alerting settings
  alerting: []
  
  # CORS settings for Open-WebUI
  allowed_headers: ["*"]
  allowed_origins: ["*"] 
  allowed_methods: ["*"]

# Router settings for load balancing and fallbacks
router_settings:
  routing_strategy: "simple-shuffle"
  model_group_alias: 
    dcs: ["dcs-codellama", "dcs-llama3"]
    code: ["dcs-codellama", "codellama"]
    general: ["dcs-llama3", "llama3"]
  
  # Fallback strategy
  fallbacks:
    - dcs-codellama: ["codellama"]
    - dcs-llama3: ["llama3"]
  
  # Health check settings
  health_check_interval: 30
  
  # Timeout for model calls
  timeout: 300

# Logging configuration
litellm_settings:
  drop_params: false
  set_verbose: true
  json_logs: true
  
  # Custom logger settings
  success_callback: []
  failure_callback: []